# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Global Configuration
exclude: ["README.md"]
timezone: Asia/Shanghai

# Jekyll Settings
excerpt_separator: <!--more-->
paginate: 5
paginate_path: ":num"
permalink: pretty
sass:
    style: :compressed

# Gems
gems:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap


# Build Command Options
# Serve Command Options
baseurl: "" # the subpath of your site, e.g. /blog

title: reinno io
email: reinno@126.com
description: reinno tech blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: reinno
github_username: reinno

# Build settings
markdown: kramdown
